### ISSUE TITLE
Source a favicon

### ISSUE THREAD

**Issue by Asday** [classy-python/ccbv#140]
CCBV (rightfully) holds a place near the start of my bookmarks bar, but without a favicon, it has to have a title, making it about 3x wider than it needs to be.  I think it would be nice if there was some sort of favicon.

Sadly, I'm no artist, so all I can do is complain.  :(

**Comment by meshy** [comment]
Given no-one talented has stepped up yet, I've used https://www.ionos.co.uk/tools/favicon-generator to do some pixel art, and have a couple of contenders.

I don't have a lot more time to spend of this for the moment, but here are the contenders I've made:

| CCBV | Classy CBV |
|--|--|
|![favicon-96x96](https://user-images.githubusercontent.com/767671/110255717-1129cb00-7f8d-11eb-8406-f5495a474cae.png)  | ![favicon-96x96](https://user-images.githubusercontent.com/767671/110255729-1b4bc980-7f8d-11eb-844a-bb9688266904.png) |


Hopefully the horror of having to live with one of them will make someone more talented step forward before I get around to adding them to the site. :laughing:

**Comment by Asday** [comment]
I'm no artist so I can't comment, but anything is better than nothing, and that's certainly a good anything.  I'd recommend you crack open a PR.

**Comment by KaratasFurkan** [comment]
@Asday I'm not an artist either and I agree that "anything is better than nothing". I was planning to open a PR after the maintainers approves this favicon but no need to wait as you recommended. If they approves, they can merge directly :slightly_smiling_face: :+1:

**Comment by ghickman** [comment]
ooh, this is great, thank you!  Some thoughts:
- since ccbv is Django-specific, can we use the Django green?
- can we add some margin around the edge of the letters? it looks a little cramped atm

@meshy – any thoughts from you?

**Comment by KaratasFurkan** [comment]
Hi @ghickman, you can check the latest version [in this PR](https://github.com/classy-python/ccbv/pull/240). Copying the image here too just to make it easier to follow:

![favicon](https://github.com/classy-python/ccbv/assets/29731420/4b876f3a-425a-4773-af84-81c455de54cd)

I actually used Django green, which is `#092E20`, described in here: https://www.djangoproject.com/community/logos/

> can we add some margin around the edge of the letters? it looks a little cramped atm

I tried to fit as much as content since favicons have limited area. If we add margins/paddings, it will be less readable. We may change the text to `CC` to fit it easily, but it's less descriptive.

I tested the latest version and I'm happy with it, here are some screenshots:
![11:41:53](https://github.com/classy-python/ccbv/assets/29731420/eff72150-2869-49f9-8877-311b0e1633c2)
![11:42:40](https://github.com/classy-python/ccbv/assets/29731420/4fcb92c6-8830-43bd-a2fd-a335f9b4ac1d)
![11:43:43](https://github.com/classy-python/ccbv/assets/29731420/70bba21a-b13b-4211-a84d-801b38547f1c)
![11:44:30](https://github.com/classy-python/ccbv/assets/29731420/dab3c7f6-7b02-44d7-93f1-09ee14436fc5)

**Comment by Asday** [comment]
FWIW I like it as it is.  Also I believe RFCs should go in #240 now it's open.

**Comment by KaratasFurkan** [comment]
> Would it get too busy if you changed the text to CBV and popped a top hat over the text?

I'm not sure about the design wise but the implementation wise, it may be a little hard for me to add it. I created this icon with a simple base that I mentioned [here](https://github.com/classy-python/ccbv/pull/240#issuecomment-2146387097). So adding an image is something else and unfortunately I'm not familiar with it.

**Comment by meshy** [comment]
> a top hat over the text?

:laughing: Maybe at some point in future, if we do a re-design.

Thanks everyone! The related PR is merged, and the favicon is live!

**Comment by ghickman** [comment]
So great to be able to spot CCBV in my tabs now, thanks all!

**Comment by Asday** [comment]
![image](https://github.com/classy-python/ccbv/assets/340276/4d6f7b88-4c17-4157-b202-b94a142215e7)


It actually looks SO clean, I love it.
