### ISSUE TITLE
django-rest-framework views?

### ISSUE THREAD

**Issue by darkpixel** [classy-python/ccbv#213]
A few days ago, I was trying to track something down in a django-rest-framework view and thought to myself "I wish there was a CCBV site for DRF".

I downloaded the source code and was surprised to find it was laid out *very* well and nothing really needed to change to get some basic DRF data in there.

I have a branch in my fork called ```drf-test``` here: https://github.com/darkpixel/ccbv/tree/drf-test

It's basically functional and uses similar management commands to populate the data.
It's not mergable because some things in CCBV appear to be Django-specific (like it currently shows DRF as "Django 3.14.0"...but I was able to easily get the info I needed.

I created a Dockerfile to quickly and easily build the environment while I was testing and added the steps to the README.

If I suddenly end up with a bunch of free time, I'll keep working on cleaning things up and toss it up on my kubernetes cluster.

If any of the changes are useful...well...it's open source. ;)

Thanks for the insanely useful project.

**Comment by meshy** [comment]
> thought to myself "I wish there was a CCBV site for DRF".

Aha! You should check out https://www.cdrf.co/

There is also https://cdf.9vo.lt/ for Django forms, but it looks like it's a bit out of date at the moment.

> surprised to find it was laid out very well and nothing really needed to change to get some basic DRF data in there.

Aw, thanks! I'm glad you found it nice to work with :)

I've been slowly refactoring this project so that it'll be easier to do this kind of fork. Some upcoming changes to come may be a little drastic, so I hope it's not too frustrating to keep your fork up to date. Perhaps ironically, I want to remove the dependency on Django, so that I can use static site generation for deployment. I hope that it'll become even easier to generate a build for any given project. In time, I may even be able to host them on this domain, but I'm not ready for that yet.

That refactor is likely to take quite some time though, so I wouldn't be too concerned.

> If any of the changes are useful...well...it's open source. ;)

Thanks! It's nice to see how easily the docker build came together.

> Thanks for the insanely useful project.

It's my pleasure :)

**Comment by darkpixel** [comment]
> Aha! You should check out https://www.cdrf.co/

LOL--that's exactly what I was looking for.  There's an hour of my life I won't get back. :)

Someone needs to do some SEO for that site.  I was hoping I would find a link to something like that in the DRF docs too, but no such luck.

> Some upcoming changes to come may be a little drastic, so I hope it's not too frustrating to keep your fork up to date.

With the link to https://www.cdrf.co/, there's no reason to keep my "sorta working" fork around.

> Thanks! It's nice to see how easily the docker build came together.

It was just a quick-and-dirty Dockerfile as a proof of concept.  If you're interested, I can whip up a decent Dockerfile as well as an example for deploying to Kubernetes.

>  In time, I may even be able to host them on this domain, but I'm not ready for that yet.

I have a few ideas on making that happen.  If things get made more generic so you an introspect a handful of projects, it would be trivial to set up a wildcard domain (i.e. *.example.tld) and have Django (or some other app) show the appropriate data.  It could be extended so you just "add" a project through an admin web interface and you'd get drf.example.tld which would show DRF content and django.example.tld would show the Django CBVs we all know and love.

**Comment by meshy** [comment]
> If you're interested, I can whip up a decent Dockerfile as well as an example for deploying to Kubernetes.

Thanks for the offer, but that's not necessary, because I'll be taking this in the direction of static generation.

I have ideas too! I'll be a different approach, but should have similar results. Watch this space!
